[algokit]
min_version = "v2.0.0"

[project]
type = 'workspace'
projects_root_path = 'projects'

[project.run]
build = ['evm-logicsig', 'evm-sdk', 'use-wallet', 'use-wallet-ui', 'frontend', 'rpc-server']

build2 = ['use-wallet', 'use-wallet-ui', 'frontend']
