packages:
  - projects/*
  - projects/use-wallet/packages/*
  - projects/use-wallet-ui/packages/*
linkWorkspacePackages: true
onlyBuiltDependencies:
  - '@algorandfoundation/puya-ts'
  - bigint-buffer
  - esbuild
  - keccak
  - sharp
  - workerd
